# Build the Application
FROM maven:3.9.5-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Run the Application
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/ares-core-*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]

