name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo for Github Actions
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Run JUnit Tests
        run: mvn test

      - name: Run Checkstyle Tests
        run: mvn checkstyle:check

      - name: Run JaCoCo Test Coverage
        run: mvn test jacoco:report

      - name: Run Integration Tests
        run: mvn verify

      - name: Build the project
        run: mvn clean compile